NoteBook:Numpy教程
作者:肖奇
日期:2019.10.25

一、快速入门教程

1.一个例子

In [4]:
import numpy as np
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


shape-数组维度

In [5]:
print(a.shape)

(3, 5)


In [6]:
print(a.ndim)

2


dtype.name-数据类型

In [7]:
print(a.dtype.name)

int32


itemsize-元素大小

In [8]:
print(a.itemsize)

4


size-数组大小

In [9]:
print(a.size)

15


In [10]:
print(type(a))

<class 'numpy.ndarray'>


In [11]:
b = np.array([6,7,8])
print(b)

[6 7 8]


2.数组创建

In [12]:
import numpy as np
a = np.array([2,3,4])
print(a)
print(a.dtype)

[2 3 4]
int32


In [13]:
b = np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


显示指定数据类型

In [14]:
c= np.array([[1,2],[3,4]],dtype=complex)
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


创建指定大小的数组

In [15]:
d = np.zeros((3,4))
e = np.ones((2,3,4))
f = np.empty((2,3))
print(d)
print(e)
print(f)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[0. 0. 0.]
 [0. 0. 0.]]


range函数创建数组

In [16]:
g = np.arange(10,30,5)
print(g)

[10 15 20 25]


linspace函数使用

In [17]:
from numpy import pi
a = np.linspace(0,2,9)
print(a)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


3.打印数组-略(上述代码已包含打印操作)

4.基本操作

In [18]:
a = np.array([20,30,40,50])
b = np.arange(4)
c= a -b
d = a + b
e = b**2
print(a)
print(b)
print(c)
print(d)
print(e)
print(a<25)

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]
[20 31 42 53]
[0 1 4 9]
[ True False False False]


*元素乘 与 @ dot  矩阵乘

In [19]:
g = a * b
h = a @ b
print(g)
print(h)

[  0  30  80 150]
260


+= * = 直接更改原数组 而不是创建新数组 

In [20]:
a += b
print(a)

[20 31 42 53]


ndarray当中的函数操作  sum  max min

In [21]:
a = np.random.random((2,3))
print(a)
print(a.min())
print(a.max())
print(a.sum())

[[0.94762655 0.33068894 0.1755214 ]
 [0.33868413 0.26878039 0.45013761]]
0.17552140127715965
0.9476265515346128
2.5114390264779534


In [22]:
a = np.arange(24).reshape(2,3,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


axis参数 沿着指定的轴进行运算

In [23]:
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a.sum(axis=2))

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[12 15 18 21]
 [48 51 54 57]]
[[ 6 22 38]
 [54 70 86]]


通函数

In [24]:
a = np.arange(3)
print(np.exp(a))
print(np.sqrt(a))

[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


索引、切片和迭代

一维

In [25]:
a = np.arange(10)**3
print(a)
print(a[2])
print(a[2:5])
a [:6:2] = 1000
print(a)
for i in a:
    print(i)

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[1000    1 1000   27 1000  125  216  343  512  729]
1000
1
1000
27
1000
125
216
343
512
729


二维

In [26]:
def f(x,y):
    return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int)
print(b)
print(b[0,1])
for i in b:#相对于第一个轴进行迭代
    print(i)
for elem in b.flat:
    print(elem)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
1
[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]
0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


模块编写测试

In [27]:
from module import hello
hello()

hello world


In [29]:
print(np.log(10))

2.302585092994046


In [30]:
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [33]:
b = np.where(a<8)
print(b)

(array([0, 0, 0, 0, 0, 1, 1, 1], dtype=int64), array([0, 1, 2, 3, 4, 0, 1, 2], dtype=int64))
